#!/bin/bash
# =============================================================================
# TitanOps Infrastructure Setup
# =============================================================================
# Interactive script that generates terraform.auto.tfvars based on what
# modules and features you want to enable. Only pay for what you use.
# =============================================================================

set -e

echo ""
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║           TitanOps Infrastructure Setup                      ║"
echo "╠══════════════════════════════════════════════════════════════╣"
echo "║  This script generates Terraform variables based on your     ║"
echo "║  module selection. You only pay for what you enable.         ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""

# Defaults
EARTHWORM="false"
TLAPIX="false"
EBEECONTROL="false"
QUACK="false"
CORRELATION="false"
NATS="false"
BRAINOPS="false"
COCKROACHDB="false"

# --- Layer 1: Module Selection ---
echo "━━━ Layer 1: Modules ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Select which autonomous modules to enable:"
echo ""

read -p "  🪱 Earthworm (health monitoring & auto-remediation)? [y/N]: " ans
[[ "$ans" =~ ^[Yy] ]] && EARTHWORM="true"

read -p "  🦡 Tlapix (certificate lifecycle management)? [y/N]: " ans
[[ "$ans" =~ ^[Yy] ]] && TLAPIX="true"

read -p "  🐝 eBeeControl (threat detection & deception)? [y/N]: " ans
[[ "$ans" =~ ^[Yy] ]] && EBEECONTROL="true"

read -p "  🦆 Quack (AI CPU scheduling via sched_ext)? [y/N]: " ans
[[ "$ans" =~ ^[Yy] ]] && QUACK="true"

echo ""

# --- Cross-module correlation ---
echo "━━━ Cross-Module Correlation ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "NATS event bus enables real-time correlation between modules."
echo "Cost: \$0 (in-cluster pod, ~15MB RAM)"
echo ""

read -p "  📡 Enable NATS event bus + Correlation Engine? [y/N]: " ans
if [[ "$ans" =~ ^[Yy] ]]; then
  NATS="true"
  CORRELATION="true"
fi

echo ""

# --- Layer 2: Intelligence ---
echo "━━━ Layer 2: Intelligence (BrainOps + CockroachDB) ━━━━━━━━━"
echo "BrainOps adds persistent agent memory powered by CockroachDB."
echo "The agent remembers past incidents, learns from resolutions,"
echo "and makes better decisions over time."
echo "Cost: CockroachDB free tier (\$0 up to 5GB + 50M RUs/month)"
echo ""

read -p "  🧠 Enable BrainOps + CockroachDB? [y/N]: " ans
if [[ "$ans" =~ ^[Yy] ]]; then
  BRAINOPS="true"
  COCKROACHDB="true"
  NATS="true"       # BrainOps requires NATS to subscribe to events
  CORRELATION="true"

  echo ""
  echo "  CockroachDB configuration:"
  read -p "    API Key (from cockroachlabs.cloud): " CRDB_API_KEY
  read -p "    SQL password for brainops user: " CRDB_PASSWORD
  read -p "    Monthly spend limit in cents [0=free tier]: " CRDB_SPEND
  CRDB_SPEND=${CRDB_SPEND:-0}
fi

echo ""

# --- Generate terraform.auto.tfvars ---
TFVARS_FILE="infra/terraform.auto.tfvars"

cat > "$TFVARS_FILE" <<EOF
# =============================================================================
# Generated by scripts/setup-infra.sh — $(date)
# Do NOT commit this file (it's in .gitignore)
# =============================================================================

# Layer 1: Module enablement
enable_earthworm   = $EARTHWORM
enable_tlapix      = $TLAPIX
enable_ebeecontrol = $EBEECONTROL
enable_quack       = $QUACK
enable_correlation = $CORRELATION

# Cross-module coordination
enable_nats = $NATS

# Layer 2: Intelligence
enable_brainops    = $BRAINOPS
enable_cockroachdb = $COCKROACHDB
EOF

# Add CockroachDB sensitive vars if enabled
if [[ "$COCKROACHDB" == "true" ]]; then
  cat >> "$TFVARS_FILE" <<EOF

# CockroachDB configuration
cockroachdb_api_key      = "$CRDB_API_KEY"
cockroachdb_sql_password = "$CRDB_PASSWORD"
cockroachdb_spend_limit  = $CRDB_SPEND
EOF
fi

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ Generated: $TFVARS_FILE"
echo ""
echo "Summary:"
echo "  Modules:  Earthworm=$EARTHWORM  Tlapix=$TLAPIX  eBeeControl=$EBEECONTROL  Quack=$QUACK"
echo "  Platform: NATS=$NATS  Correlation=$CORRELATION"
echo "  Intelligence: BrainOps=$BRAINOPS  CockroachDB=$COCKROACHDB"
echo ""
echo "Next steps:"
echo "  cd infra"
echo "  terraform init"
echo "  terraform plan"
echo "  terraform apply"
echo ""
